# Generated by Django 4.2.5 on 2023-10-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authuser',
            table='Users',
        ),
    ]
