# Generated by Django 4.2.5 on 2023-10-24 11:42

from django.db import migrations, models
import services.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_authuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[services.validators.validate_username]),
        ),
    ]
