# Generated by Django 5.0.1 on 2024-02-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_authuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
