# Generated by Django 4.2.5 on 2023-10-16 16:22

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale_advertisement', '0007_alter_saleadvertisement_advertisement_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteAdvertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisements_amount', models.PositiveIntegerField(default=0)),
                ('adding_date', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(auto_now=True), size=None)),
                ('advertisements', models.ManyToManyField(default=0, to='sale_advertisement.saleadvertisement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
