# Generated by Django 5.0.1 on 2024-04-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteAdvertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adding_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'FavouriteAdvertisements',
            },
        ),
    ]
