# Generated by Django 4.2.5 on 2023-10-18 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale_advertisement', '0009_alter_saleadvertisement_users_checked_advertisement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteAdvertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisements_amount', models.PositiveIntegerField(default=0)),
                ('adding_date', models.DateTimeField()),
                ('advertisements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale_advertisement.saleadvertisement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FavouriteAdvertisements',
            },
        ),
    ]
