# Generated by Django 4.2.5 on 2023-10-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourite_advertisements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouriteadvertisements',
            name='advertisements_amount',
        ),
    ]
