# Generated by Django 5.0.1 on 2024-04-11 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favourite_advertisements', '0001_initial'),
        ('sale_advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteadvertisements',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale_advertisement.saleadvertisement'),
        ),
    ]
