# Generated by Django 4.2.5 on 2023-10-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourite_advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favouriteadvertisements',
            table='FavouriteAdvertisements',
        ),
    ]
