# Generated by Django 4.2.5 on 2023-10-17 10:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite_advertisements', '0002_alter_favouriteadvertisements_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteadvertisements',
            name='adding_date',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None),
        ),
    ]
