# Generated by Django 4.2.5 on 2023-10-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite_advertisements', '0003_rename_advertisements_favouriteadvertisements_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteadvertisements',
            name='adding_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
