# Generated by Django 4.2.5 on 2023-10-18 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favourite_advertisements', '0004_alter_favouriteadvertisements_adding_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteadvertisements',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
