# Generated by Django 5.0.1 on 2024-04-11 11:27

import sale_advertisement.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'AdvertisementsUsers',
            },
        ),
        migrations.CreateModel(
            name='SaleAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement_title', models.CharField(max_length=150)),
                ('advertisement_description', models.TextField()),
                ('advertisement_location', models.CharField(max_length=150)),
                ('publish_date', models.DateTimeField(auto_now=True)),
                ('advertisement_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[sale_advertisement.validators.price_validator])),
                ('is_new', models.BooleanField()),
                ('views_amount', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'Advertisements',
            },
        ),
    ]
