# Generated by Django 5.0.1 on 2024-04-11 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale_advertisement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementsusers',
            name='user_checked_advertisements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleadvertisement',
            name='advertisement_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleadvertisement',
            name='users_checked_advertisement',
            field=models.ManyToManyField(blank=True, default=None, related_name='checked_advertisements', through='sale_advertisement.AdvertisementsUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertisementsusers',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale_advertisement.saleadvertisement'),
        ),
    ]
