# Generated by Django 4.2.5 on 2023-10-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleadvertisement',
            name='is_new',
            field=models.BooleanField(null=True),
        ),
    ]
