# Generated by Django 4.2.5 on 2023-10-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_advertisement', '0002_saleadvertisement_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleadvertisement',
            name='views_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='saleadvertisement',
            name='is_new',
            field=models.BooleanField(),
        ),
    ]
