# Generated by Django 4.2.5 on 2023-10-14 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale_advertisement', '0004_remove_saleadvertisement_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleadvertisement',
            name='users_checked_advertisement',
            field=models.ManyToManyField(default=None, related_name='visitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleadvertisement',
            name='advertisement_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
