# Generated by Django 4.2.5 on 2023-10-15 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale_advertisement', '0005_saleadvertisement_users_checked_advertisement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleadvertisement',
            name='advertisement_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
