# Generated by Django 4.2.5 on 2023-10-16 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale_advertisement', '0006_alter_saleadvertisement_advertisement_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleadvertisement',
            name='advertisement_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
